### ISSUE TITLE
Fix trailing newline issue

### ISSUE THREAD

**Issue by M3t0r** [M3t0r/tpl#4]
In https://github.com/M3t0r/tpl/blob/feceeed182f1c2553b827d8f431f6be800204250/tpl/__init__.py#L72 `tpl` always adds a trailing newline instead of respecting what the template has. I added this to have nicer output on the command line, but it turns out Jinja has a setting if it should keep the last newline, if any. It's called `keep_trailing_newline` and is part of the [`jinja2.Environment`](http://jinja.pocoo.org/docs/2.10/api/#jinja2.Environment).

We should add tests to see if `tpl` only prints a newline if one is actually present in the template.

**Comment by praveensvsrk** [comment]
Is peeking into the stream to find the last character (or the last line in case of a trailing new line with spaces) a good idea?

**Comment by M3t0r** [comment]
I think just providing a `jinja2.Environment` with `keep_trailing_newline` set to true will tell Jinja to take care of that. That would make our part very simple.
