### ISSUE TITLE
Add link to Jinja2 Template Designer manual

### ISSUE THREAD

**Issue by M3t0r** [M3t0r/tpl#5]
I know where to find it, you know where to find it, let's make it easier to find it for everyone by adding a link to the `--help` output of `tpl`. It'd be great if that actually links to the Jinja version that `tpl` uses.

**Comment by loudambiance** [comment]
II'll take this one on. Do you have a preferred format for the link in the help text?

**Comment by loudambiance** [comment]
#9 Added pull request.

Added additional commit to update README.md to account for automated build test. The README.md will need to be updated as newer versions of Jinja are included, and could cause the testing to fail in scenarios where one user has 2.10, and some other user has a future version 2.11. 

I am not sure how this should be handled, I understand that you want to make sure the README matches the output of the command, however, as versions of Jinja diverge in the future, this may become more difficult. I chose to not make assumptions on how you want this handled for now, as the test will pass, for now.

**Comment by M3t0r** [comment]
I was thinking about transforming the current test into a unit test and mock `jinja2.__version__` to `latest`. That way the README.md always points http://jinja.pocoo.org/docs/latest/, but the output in the installed program to the actually used version.

Do you wanna try that? Otherwise I'll give it a shot 😄

**Comment by loudambiance** [comment]
Make sure I understand, you want a unit test that compares the README.md text with a predetermined text that uses the link "http://jinja.pocoo.org/docs/latest/", and include that link in the README.md, and have the actual output of --h/--help link to the installed version (ie  http://jinja.pocoo.org/docs/2.10/)? If so, I think I can pop that out. One last thing, I thought of a bit ago, there is a scenario where the dynamic link fails using `jinja2.__version__`, if the person running tpl has a development release of jinja, it will return 2.11.dev (or something similar), and there will be no documentation for that. Would you like me to check for the presence of dev in the version string, and redirect the url to "latest" instead? 

Also, was the format I used okay?

**Comment by M3t0r** [comment]
`jq` has the manual link between the usage and the options, and that is what I feel is the "natural" way. But I haven't checked other programs with a bit of explanatory text in their `--help` messages.

I just installed the master branch of Jinja and it is listed as `2.11.dev0`. Got catch! I would have ignored that corner case, but I guess we could simply check `if "dev" in jinja.__version__` and then link to http://jinja.pocoo.org/docs/dev/.

But yes, the one in the README should link to the latest documentation. But it should also be up-to-date with the actual output of `--help` (which is why I wrote that test). To achieve that I would suggest we mock the version string of Jinja in that test. Because in the normal output of `--help` I'd like it to link to the used version.

Have fun 😃

**Comment by loudambiance** [comment]
Check out this #10 pull request and see if it meets your needs.

I updated the URL in the help test to do a string check to see if the version of `jinja2.__version__` contains dev, if so, it inserts dev as the version in the url, instead of what version returns. I also updated the test case to check against a static string, comparing it to expected output of from -h, with the url /latest/.

**Comment by M3t0r** [comment]
Done in #10 by @loudambiance. Thanks!
