### ISSUE TITLE
Port to Python 3.5

### ISSUE THREAD

**Issue by M3t0r** [M3t0r/tpl#6]
To make `tpl` available to a wider userbase it should be able to run on Python 3.5. That is the [latest version in Debian stable](https://packages.debian.org/stretch/python3) and Debian stable feels like a good platform to support.

There already is a CI test for 3.6 (and 3.7 if travis would support it) so the main work should be to replace all `f"strings"` with `"string".format()`s.

**Comment by AlexanderDavid** [comment]
Would this just entail trying to run the project with python 3.5 and fixing the errors when they come up? If so I would like to take a stab at this.

**Comment by M3t0r** [comment]
I feel confident in the end-to-end tests in [`tests/cli`](https://github.com/M3t0r/tpl/tree/master/tests/cli), so yeah, when they pass and they are continuously being executed in 3.5 (I think just adding `3.5` to the list in `.travis.yml`) I'm satisfied.
